language: java
sudo: false
install: true
jdk: oraclejdk7
script: ./travis.sh

env:
  - TARGET=CI
  - TARGET=IT IT_CATEGORY=Category1
  - TARGET=IT IT_CATEGORY=Category2
  - TARGET=IT IT_CATEGORY=Category3
  - TARGET=IT IT_CATEGORY=Category4
  - TARGET=IT IT_CATEGORY=Category5
  - TARGET=WEB


matrix:
  fast_finish: true

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sonar
    - 'server/sonar-web/node'
    - 'server/sonar-web/node_modules'

before_cache:
  # remove all the artifacts (JAR, ZIP) that are installed in local repo because of mvn deploy
  - rm -rf $HOME/.m2/repository/org/sonarsource/sonarqube

notifications:
  email: false
  webhooks:
    - secure: "UsCLBZ1wEQkEPhlIETa8127r+/e+p0NFQR2f6XxvpDdyogQsgsmdz5nOjdttrWItbNNPGyZu+d/W6a/BckpS+hZBgbGbnwKe2Ht6VVIWvhDgcyXpM19CQqfXQVaGpnLTDwXy4ajases1aqsvGaUrljII74phkij/AhnIURxH/FY="
