language: java
sudo: false
install: true
jdk: oraclejdk7
script: ./travis.sh

env:
  - JOB=H2
  - JOB=POSTGRES
  - JOB=MYSQL
  - JOB=WEB
  - JOB=ITS IT_CATEGORY=batch
  - JOB=ITS IT_CATEGORY=plugins
  - JOB=ITS IT_CATEGORY=issue_analysis
  - JOB=ITS IT_CATEGORY=administration_qualitygate
  - JOB=ITS IT_CATEGORY=server_updatecenter

matrix:
  fast_finish: true

cache:
  directories:
    - '$HOME/.m2/repository'
    - 'server/sonar-web/node'
    - 'server/sonar-web/node_modules'

before_cache:
  - 'rm -rf $HOME/.m2/repository/org/codehaus/sonar'
  - 'rm -f server/sonar-web/npm-debug.log'

notifications:
  email: false
